name: 'Check style'
description: 'Check prose style with vale'

inputs:
  git-token:
    description: 'a token for git commands'
    required: true
  files-to-check:
    description: 'files to check'
    type: string
    default: '["modules/ROOT/pages", "modules/ROOT/partials"]'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ inputs.files-to-check }}
          reporter: github-pr-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}