name: 'Deploy'
description: 'Upload to surge'

inputs:
  package-script:
    description: 'The name of the script to run in package.json '
    type: string
    default: 'build-verify'
  deploy-id:
    description: 'The PR number if workflow called by a PR'
    required: true
    type: string
    default: 'na'
  retain-artifacts:
    description: 'The number of days to retain artifacts'
    required: true
    type: number
    default: 7
  surge-deploy-url:
    description: 'The surge.sh URL'
    required: true
    type: string

# outputs:
#   copied-files: 
#     description: "Number of files copied"
#     value: ${{ steps.random-number-generator.outputs.filesNo }}

runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/ExecuteSomething.sh
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=filesNo::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/CopyFiles.sh
      shell: bash