name: 'Build and deploy docs pr'
description: 'Builds and verifies docs'

inputs:
  package-script:
    description: 'The name of the script to run in package.json '
    type: string
    default: 'build-verify'
  fail-on-warnings:
    description: 'Fail the Antora verification if the log contains warnings'
    type: boolean
    default: false
  retain-artifacts:
    description: 'The number of days to retain artifacts'
    required: true
    type: number
    default: 7
  surge-deploy-id:
    description: 'The PR number if called by a PR'
    required: true
    type: string
    default: 'na'
  surge-deploy-url:
    description: 'The surge.sh URL'
    required: true
    type: string


# outputs:
#   copied-files: 
#     description: "Number of files copied"
#     value: ${{ steps.random-number-generator.outputs.filesNo }}

runs:
  using: "composite"
  steps: 

    # checkout
    
    - uses: actions/checkout@v3


    # build

    - uses: ./.github/actions/build
      with:
        package-script: ${{ inputs.package-script }}


    # verify

    - uses: ./.github/actions/verify
      with:
        failOnWarnings: ${{ inputs.fail-on-warnings }}

    # check links

    - uses: ./.github/actions/lint/links
      with:
        # git-token: ${{ secrets.PR_COMMENT_TOKEN }}
        surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
        base: ${{ github.base_ref }}
        head: ${{ github.head_ref }}


