# docs-build-verify.yml

# 1. Build docs using preview.yml (which builds for the current branch)
# 2. Check for warnings and errors in the Antora log
# 3. Run link-checker against the branch docs

# This is an example of the docs-build-verify.yml workflow available from the recrwplay org
name: "Documentation Publish"

on:
  push:
    branches:
      - main

jobs:
       
  # build and verify the asciidoc
  build-verify:
    name: Verify Antora log
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # build and verify

      - id: build-verify
        name: Build and verify
        uses: ./.github/actions/docs/docs-build-verify
        with:
          package-script: 'publish-verify'
          surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ GITHUB_REF_NAME	}}'
          surge-deploy-id: '${{ GITHUB_REF_NAME	}}'
          fail-on-warnings: true

  # publish HTML
  publish-html:
    name: Publish ${{ github.event.repository.name}} HTML
    runs-on: ubuntu-latest
    steps:
      - name: Download Antora output
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: build/

      # - name: Publish
      #   uses:
      # # tbc...