# This is an example of the docs-pr.yml workflow available from the recrwplay org
name: "Vale"

on:
  pull_request:

jobs:

  # set-outputs:
  #   runs-on: ubuntu-latest
  #   # Map a step output to a job output
  #   outputs:
  #     pages-partials: ${{ steps.get-pages-partials.outputs.pages-partials }}
  #   steps:
  #     - name: Check out PR branch
  #       uses: actions/checkout@v3

  #     - id: get-pages-partials
  #       run: |
  #         valefiles="$(gh pr view ${{ github.event.number }} --json files --jq 'map(.[] | select(.path | test("modules/ROOT/(pages|partials)"; "i") ) | .path) ')"
  #         echo "$valefiles"
  #         echo "pages-partials=$valefiles" >> $GITHUB_OUTPUT
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: get-pages-partials
        run: |
          valefiles="$(gh pr view ${{ github.event.number }} --json files --jq 'map(.[] | select(.path | test("modules/ROOT/(pages|partials)"; "i") ) | .path) ')"
          echo "$valefiles"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ valefiles }}
          reporter: github-pr-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
