# This is an example of the docs-pr.yml workflow available from the recrwplay org
name: "Verify PR"

on:
  pull_request:

jobs:

  build-verify-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: build-verify
        name: Build and verify
        uses: ./.github/actions/docs-pr
        with:
          package-script: 'build-verify'
          surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
          surge-deploy-id: ${{ github.event.number }}
          check-new-links: false
          check-all-links: false
          fail-on-warnings: true

          
    # deploy
      - id: deploy
        name: Deploy
        if: success() || failure()
        uses: ./.github/actions/deploy
        with:
          surge-token: ${{ secrets.SURGE_TOKEN }}
          surge-deploy-url: ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh


      # - id: deploy
      #   name: Deploy to surge
      #   run: |
      #     npm install -g surge
      #     deployurl=${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh
      #     surge ./build/site $deployurl --token ${{ secrets.SURGE_TOKEN }}



        # uses: ./.github/actions/deploy
        # with:
        #   surge-tokem: ${{ secrets.SURGE_TOKEN }}
        #   surge-deploy-url: ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh




