# This is an example of the docs-build-verify.yml workflow available from the recrwplay org
name: "Verify PR"

on:
  push:
    branches:
      - main

jobs:
       
  build-verify:
    name: Verify Antora log
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # build and verify

      - id: build-verify
        name: Build and verify
        uses: ./.github/actions/docs/docs-build-verify
        with:
          package-script: 'publish-verify'
          surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ GITHUB_REF_NAME	}}'
          surge-deploy-id: '${{ GITHUB_REF_NAME	}}'
          fail-on-warnings: true

  # check all links
  check-links-publish:
    name: Check links
    needs: build-verify
    runs-on: ubuntu-latest
    steps:

      - name: Download Antora log
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: build/
      
    #   if: success() || failure() && contains( github.event.pull_request.labels.*.name, 'check-links')
    #   name: Check links
      #   run: npm run check-links


      # lint tests - new links

      # - id: lint
      #   name: Lint
      #   if: success() || failure()
      #   uses: ./.github/actions/docs/lint/links
      #   with:
      #     git-token: ${{ secrets.PR_COMMENT_TOKEN }}
      #     surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
      #     base: ${{ github.base_ref }}
      #     head: ${{ github.head_ref }}

      # - id: vale
      #   name: Vale
      #   if: success() || failure()
      #   uses: ./.github/actions/docs/lint/vale
      #   with:
      #     git-token: ${{ secrets.PR_COMMENT_TOKEN }}
      #     surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
      #     base: ${{ github.base_ref }}
      #     head: ${{ github.head_ref }}
      # - id: deploy
      #   name: Deploy to surge
      #   run: |
      #     npm install -g surge
      #     deployurl=${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh
      #     surge ./build/site $deployurl --token ${{ secrets.SURGE_TOKEN }}



        # uses: ./.github/actions/docs/deploy
        # with:
        #   surge-tokem: ${{ secrets.SURGE_TOKEN }}
        #   surge-deploy-url: ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh




