# Documentation Style Guide Lint
# Uses Vale to lint documentation against the Documentation Style Guide
# Current POC uses the Google style guide as a base set of rules
# See .vale.ini for the current set of rules

name: "Documentation Style Guide Lint"

on:
  pull_request:
  workflow_dispatch:
    inputs:
      files:
        description: 'The files to lint'
        default: "['modules/ROOT/pages/', 'modules/ROOT/partials/']"
        type: string

jobs:

  vale-config:
    name: Get file list for vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get file list from PR
        id: get-files-to-lint
        if: github.event.pull_request
        run: |
          files="$(gh pr view ${{ github.event.number }} --json files --jq 'map(.[] | select(.path | test("modules/ROOT/(pages|partials)"; "i") ) | .path) ')"
          echo "$files"
          echo "files-to-lint=$files" >> $GITHUB_OUTPUT 
          echo "reporter=github-pr-check" >> $GITHUB_OUTPUT      
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Get file list from workflow_dispatch
        id: get-files-from-input
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "files-to-lint=${{ github.event.inputs.files }}" >> $GITHUB_OUTPUT
          echo "reporter=github-check" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    outputs:
      files-to-lint: ${{ steps.vale-config.outputs.files-to-lint }}
      reporter: ${{ steps.vale-config.outputs.reporter }}

  vale:
    name: Lint with Vale
    runs-on: ubuntu-latest
    needs: files-to-lint
    if: ${{ needs.vale-config.outputs.files-to-lint != '[]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ needs.vale-config.outputs.files-to-lint }}
          reporter: ${{ needs.vale-config.outputs.reporter }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
