# docs-branch-verify.yml

# 1. Build docs using preview.yml (which builds for the current branch)
# 2. Check for warnings and errors in the Antora log
# 3. Run link-checker against the branch docs

name: "Verify Documentation Branch"

on:
  push:
    branches:
      - main
      - dev

jobs:
       
  build-verify:
    name: Verify Antora log
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # build and verify

      - id: build-verify
        name: Build and verify
        uses: ./.github/actions/docs/docs-build-verify
        with:
          package-script: 'build-verify'
          surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ GITHUB_REF_NAME	}}'
          surge-deploy-id: '${{ GITHUB_REF_NAME	}}'
          fail-on-warnings: true

  # check all links
  check-links-publish:
    name: Check links
    needs: build-verify
    runs-on: ubuntu-latest
    steps:
      - name: Download Antora output
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: build/

      - run: npm install github:recrwplay/link-checker#v0.1.1  

      - run: npm run check-links-publish
      


  # vale:
  #   name: Vale
  #   uses: ./.github/actions/docs/lint/vale

