# docs-pr-links.yml
# Runs the link checker on the PR branch to verify files that contain new or changed links

name: "Documentation PR link-checker"

on:
  pull_request:

jobs:

  check-diff-links:
    name: Check new and changed links
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0


      - id: antora-component-name
        name: Read antora component name
        uses: jbutcher5/read-yaml@main
        with:
          file: './antora.yml'
          key-path: '["name"]'

      - id: antora-component-version
        name: Read antora component version
        uses: jbutcher5/read-yaml@main
        with:
          file: './antora.yml'
          key-path: '["version"]'

      # get files with link: from the diff
      - run: git fetch origin ${{ github.base_ref }}


      - id: get-link-count
        run: |
          linkcount="$(git diff origin/${{ github.base_ref }}..HEAD -Glink: --name-only | wc -l)"
          echo "$linkcount"
          echo "link-count=$linkcount" >> $GITHUB_OUTPUT

      - run: npm install

      - name: Get PR diff file list
        run: 'git diff origin/${{ github.base_ref }}..HEAD -Glink: --name-only | npx pino-pretty | perl -ne "if (/^modules\/ROOT\/pages\/(.*?)(index)?\.adoc/) { print \"localhost:8000/${{ steps.antora-component-name.outputs.data }}/${{ steps.antora-component-version.outputs.data }}/\$1\n\" }" > diff-links.txt'

      - name: Check links
        if: ${{ steps.get-link-count.outputs.link-count > 0 }}
        run: npm run check-links-diff

      # upload diff file list

      - name: Save diff output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff
          path: diff-links.txt

    outputs:
      link-count: ${{ steps.get-link-count.outputs.link-count }}

