# Documentation Style Guide Lint
# Uses Vale to lint documentation against the Documentation Style Guide
# Current POC uses the Google style guide as a base set of rules
# See .vale.ini for the current set of rules

name: "Documentation Style Guide Lint"

on:
  pull_request:

jobs:

  files-to-lint:
    name: Get file list for vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get file list
        id: get-files-to-lint
        run: |
          files="$(gh pr view ${{ github.event.number }} --json files --jq 'map(.[] | select(.path | test("modules/ROOT/(pages|partials)"; "i") ) | .path) ')"
          echo "$files"
          echo "files-to-lint=$files" >> $GITHUB_OUTPUT      
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    outputs:
      files-to-lint: ${{ steps.get-files-to-lint.outputs.files-to-lint }}

  vale:
    name: Lint with Vale
    runs-on: ubuntu-latest
    needs: files-to-lint
    if: ${{ needs.files-to-lint.outputs.files-to-lint != '[]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.get-pages-partials.outputs.vale-files }}
          reporter: github-pr-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
